spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pixDataBase?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 91528641Gui@
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 9200
